project_id = "woqyhugzztdjpkfwkolu"

[functions.reset-user-password]
verify_jwt = false

[functions.autentique-webhook]
verify_jwt = false

[functions.autentique-sync-all]
verify_jwt = false

[functions.soc-full-sync-scheduled]
verify_jwt = false