export const CONTRACT_PLACEHOLDERS = [
  { key: 'RAZAO_SOCIAL', label: 'Razão Social' },
  { key: 'NOME_FANTASIA', label: 'Nome Fantasia' },
  { key: 'CNPJ', label: 'CNPJ' },
  { key: 'ENDERECO', label: 'Endereço completo' },
  { key: 'CEP', label: 'CEP' },
  { key: 'CIDADE', label: 'Cidade' },
  { key: 'ESTADO', label: 'Estado (UF)' },
  { key: 'NUMERO_PROPOSTA', label: 'Número da Proposta' },
  { key: 'VALOR_MENSAL', label: 'Valor Mensal' },
  { key: 'QTD_VIDAS', label: 'Quantidade de Vidas' },
  { key: 'VALOR_EXCEDENTE', label: 'Valor por Vida Excedente' },
  { key: 'DATA_INICIO', label: 'Data de Início' },
  { key: 'DATA_FIM', label: 'Data de Término' },
  { key: 'VIGENCIA', label: 'Vigência (meses)' },
  { key: 'INDICE_REAJUSTE', label: 'Índice de Reajuste' },
  { key: 'PRAZO_AVISO', label: 'Prazo de Aviso Prévio' },
  { key: 'DIA_COBRANCA', label: 'Dia de Cobrança' },
  { key: 'MULTA', label: '% de Multa' },
  { key: 'JUROS', label: '% de Juros' },
  { key: 'VALOR_KM', label: 'Valor KM Rodado' },
  { key: 'REPRESENTANTE', label: 'Representante Legal' },
  { key: 'CPF_REPRESENTANTE', label: 'CPF do Representante' },
  { key: 'TESTEMUNHA_1', label: 'Testemunha 1' },
  { key: 'CPF_TESTEMUNHA_1', label: 'CPF Testemunha 1' },
  { key: 'TESTEMUNHA_2', label: 'Testemunha 2' },
  { key: 'CPF_TESTEMUNHA_2', label: 'CPF Testemunha 2' },
] as const;

export type PlaceholderKey = (typeof CONTRACT_PLACEHOLDERS)[number]['key'];
